### ISSUE TITLE
OpenURI::HTTPError: 404 Not Found

### ISSUE THREAD

**Issue by DonGiulio** [herval/yahoo-finance#28]
Hello, 

I used this gem for a while, but when using it today I got: 

    OpenURI::HTTPError: 404 Not Found
     /Users/giulio/.rvm/gems/ruby-2.2.3/gems/yahoo-finance-1.0.0/lib/yahoo-finance.rb:132:in `read_historical'
     /Users/giulio/.rvm/gems/ruby-2.2.3/gems/yahoo-finance-1.0.0/lib/yahoo-finance.rb:84:in `historical_quotes'

and if I navigate manually to `http://ichart.finance.yahoo.com/table.csv` I get an error page. 

Did yahoo discontinue the service? What's going on? 

If not yahoo what else could I use to download price data (daily, and intra day)? 

Thanks, 
G

**Comment by bcoles** [comment]
Hi @DonGiulio 

Are you still having this issue? If so, can you share the code you're using? I haven't been able to reproduce this error.

It's worth noting that browsing directly to `table.csv` results in a 404 unless parameters are provided. For example:

* hxxps://ichart.finance.yahoo.com/table.csv?s=AAPL&g=m&ignore=.csv

Some test cases:

```
#!/usr/bin/env ruby
require 'yahoo-finance'
yahoo_client = YahooFinance::Client.new

# monthly historical data
data = yahoo_client.historical_quotes("AAPL", { raw: false, period: :monthly })
puts data.inspect

# entire historical data
data = yahoo_client.historical_quotes("AAPL")
puts data.inspect
```
